---
title: "tidyCpp Motivation"
author: "Dirk Eddelbuettel"
date: "Initial (draft) version dated September 2020"
output:
  minidown::mini_document:
    framework: water
    code_folding:
      source: show
      output: show
      message: hide
      warning: hide
      error: hide
vignette: >
  %\VignetteIndexEntry{tidyCpp Motivation}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introducing tidyCpp

This package offers a simple, small and clean C++ layer over the C API offered by R. This vignette
highlights a few usage examples, often taken from the [_Writing R Extensions_ vignette that comes
with R](https://cran.r-project.org/doc/manuals/r-release/R-exts.html), to highlight some features.

`tidyCpp` has no further dependencies on any other package.  It can however be used with
[Rcpp](https://wwww.rcpp.org) simply to take advantage of its helper functions `cppFunction()` or
`sourceCpp()`.

`tidyCpp` is still fairly young and small.  Please free to contribute by make suggestions, or
sending bugfixes or extension proposals.

### Snippet One: dimnames

This example comes from [Writing R Extension, Section
5.9.4](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Attributes) which highlights
attribute setting from the C API.

It takes two (named) numeric vectors, computes the outer product matrix and uses the names to set
row- and column names. Note that we modified the existing example ever so slight by ensuring (as is
frequently done) remapping of symbols. For example, `length` (which can clash easily with existing
symbols in the global namespace) is now `Rf_length`.  We also added an `export` tag for `Rcpp`
simply to facilitate integration into R.  No Rcpp header or data structures are used; we simply rely
on its logic in getting C or C++ source into R.

:::::: {.columns}
::: {.column width="49.5%"}

#### Using the C API for R

```c++
#include <R.h>
#include <Rinternals.h>

// [[Rcpp::export]]
SEXP out(SEXP x, SEXP y)
{
  int nx = Rf_length(x), ny = Rf_length(y);
  SEXP ans = PROTECT(Rf_allocMatrix(REALSXP,
                                    nx, ny));
  double *rx = REAL(x), *ry = REAL(y),
    *rans = REAL(ans);

  for(int i = 0; i < nx; i++) {
    double tmp = rx[i];
    for(int j = 0; j < ny; j++)
      rans[i + nx*j] = tmp * ry[j];
  }

  SEXP dimnames = PROTECT(Rf_allocVector(VECSXP,2));
  SET_VECTOR_ELT(dimnames, 0,
                 Rf_getAttrib(x, R_NamesSymbol));
  SET_VECTOR_ELT(dimnames, 1,
                 Rf_getAttrib(y, R_NamesSymbol));
  Rf_setAttrib(ans, R_DimNamesSymbol, dimnames);

  UNPROTECT(2);
  return ans;
}
```

:::
::: {.column width="1%"}
\
<!-- an empty Div (with a white space), serving as a column separator -->
:::
::: {.column width="49.5%"}

#### Using tidyCpp


```c++
#include <tidyCpp>
// [[Rcpp::depends(tidyCpp)]]

// [[Rcpp::export]]
SEXP out(SEXP x, SEXP y)
{
  int nx = R::length(x), ny = R::length(y);
  SEXP ans = R::Shield(R::allocMatrixReal(nx, ny));
  double *rx = R::numericPointer(x),
    *ry = R::numericPointer(y),
    *rans = R::numericPointer(ans);

  for(int i = 0; i < nx; i++) {
    double tmp = rx[i];
    for(int j = 0; j < ny; j++)
      rans[i + nx*j] = tmp * ry[j];
  }

  SEXP dimnames = R::Shield(R::allocVectorList(2));
  R::setVectorElement(dimnames, 0, R::getNames(x));
  R::setVectorElement(dimnames, 1, R::getNames(y));
  R::setDimNames(ans, dimnames);
  return ans;
}
```
:::
::::::

Some key differences:

- a single header `tidyCpp`: simple and clean;
- no `PROTECT` and `UNPROTECT` with manual calling of the number of calls made: C++ takes care of
  that for us via `Shield` which we borrowed (in a simplified form) from Rcpp;
- no `Rf_*` calls: everything used comes from a clean new namespace `R` and is easily identified;
- types are made explicit in the name of the called function sequence rather than enum;
- consistent naming that aligns with language convention:
    - _types_ such as `Shield` are capitalized, and
    - _verbs_ such as the allocators or converters are snakeCase;
- overall less wordy and shorter, _e.g._, `R::getNames(x)` instead of `Rf_getAttrib(x, R_NamesSymbol)`


Note that the use of `Rcpp::export` does not imply use of Rcpp data structures.  We simply take
advantaged of the tried and true code generation to make it easy to call the example from R. You can
copy either example into a temporary file and use `Rcpp::sourceCpp("filenameHere")` on it to run the
example.
