# GitHub Action using r-travis from https://eddelbuettel.github.io/r-travis/

name: R-CMD-check

on:
  push:
  pull_request:

env:
  USE_BSPM: "true"
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  build:
    strategy:
      matrix:
        config:
          - {os: macOS-latest}
          - {os: ubuntu-latest}

    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Download
      run: curl -OLs https://eddelbuettel.github.io/r-travis/run.sh
    - name: Mode
      run: chmod 0755 run.sh
    - name: Bootstrap
      run: ./run.sh bootstrap
    - name: Dependencies
      run: ./run.sh install_all
    - name: Test
      run: ./run.sh run_tests
